### ISSUE TITLE
Mouse pointer jumps.

### ISSUE THREAD

**Issue by 91he** [ClementGre/ThreeFingersDragOnWindows#1]
Mouse pointer jumps very offen while dragging.

**Comment by ClementGre** [comment]
I noticed that it sometimes jumps when releasing the fingers and replacing them on the touchpad, continuing the drag.
Are you talking about this ? Or does it jumps even when you don't release fingers ?

**Comment by ClementGre** [comment]
By the way, it is normal if the pointer jumps when dragging the ThreeFingersDragOnWindows app window title bar, I don't know why, but because it is the app itself, it can't work properly when you drag the window.

But it should work properly on any other window or on the desktop !

**Comment by ClementGre** [comment]
Ok,
I had the same issue on my laptop, but only something like once in twenty try.
I can't currently work on fixing this bug, but I'll try later.

Thanks for the report, I didn't think that it could appear more often on others touchpads.

**Comment by 91he** [comment]
> Ok, I had the same issue on my laptop, but only something like once in twenty try. I can't currently work on fixing this bug, but I'll try later.
> 
> Thanks for the report, I didn't think that it could appear more often on others touchpads.

![image](https://user-images.githubusercontent.com/5378476/182229159-8cadb17d-015b-4cfc-b66f-9cab0014b163.png)
I fixed the issue like this, it works good for me.

**Comment by ClementGre** [comment]
Thank you very much !

I'll check this out and make a new release when I'm back home.

**Comment by hans000** [comment]
> 

perhaps it reproduce when resize window (maybe 100%)

**Comment by hans000** [comment]
> Ok, I had the same issue on my laptop, but only something like once in twenty try. I can't currently work on fixing this bug, but I'll try later.
> 
> Thanks for the report, I didn't think that it could appear more often on others touchpads.

perhaps it reproduce when resize window (maybe 100%)

**Comment by ClementGre** [comment]
I'm afraid I will not be able to update this app anymore.

I developed it in three days when I had a Windows laptop, but I don't have it anymore, and I figured out I had no wireless trackpad at home.

I hope someone will be able to fork this app to fix this bug.
Thank you !

**Comment by gurinderhans** [comment]
Hey @ClementGre , great work on this app! I took inspiration from your project and wrote my own version which also fixes the bugs present in this project (ie. mouse pointer jump, not being able to drag certain apps/views). Please feel free to incorporate my fixes into your app if you choose.

I'm adding a link to my project here, hope its okay with you!
https://github.com/gurinderhans/threefingerdrag

**Comment by kml0798** [comment]
> Hey @ClementGre , great work on this app! I took inspiration from your project and wrote my own version which also fixes the bugs present in this project (ie. mouse pointer jump, not being able to drag certain apps/views). Please feel free to incorporate my fixes into your app if you choose.
> 
> I'm adding a link to my project here, hope its okay with you! https://github.com/gurinderhans/threefingerdrag

**Comment by kml0798** [comment]
> Hey @ClementGre , great work on this app! I took inspiration from your project and wrote my own version which also fixes the bugs present in this project (ie. mouse pointer jump, not being able to drag certain apps/views). Please feel free to incorporate my fixes into your app if you choose.
> 
> I'm adding a link to my project here, hope its okay with you! https://github.com/gurinderhans/threefingerdrag

Thanks for ur contribution! i have an idea about a new gesture which is compatible with windows original gesture, but since its developed over the buggy version, i tried to  read ur code but end up with giving up T_T. could u try it out in my repository and maybe consider add it to ur project?

**Comment by ClementGre** [comment]
Hi,

this issue happens because, when replacing fingers on the touchpad, you generally send a one or two finger input while removing/placing fingers.
Therefore, this allows me to detect a fingers replacement, and to reset the coordinates. But sometimes, you don't generate these events (removing exactly all fingers at the same time), and in these cases, I can't detect a fingers replacement, and the cursor is then bound to jump in function of the fingers replacement shift.

I added a threshold that prevent this issue, just like @91he did, and it now works perfectly, without any bug.

I'll make a release in a few days !
