### ISSUE TITLE
Brilliant work! I draw a simple icon in Fluent UI style.

### ISSUE THREAD

**Issue by neoncloud** [ClementGre/ThreeFingersDragOnWindows#15]
![three_drag](https://user-images.githubusercontent.com/13192255/207499508-460dcc91-60f0-49a3-9086-5e024656684d.png)
Also I put my .ai source file here so you can modify it. Hope you like it.
[three_drag.zip](https://github.com/ClementGre/ThreeFingersDragOnWindows/files/10224067/three_drag.zip)

**Comment by ClementGre** [comment]
That's great !
You can do a pull request to update the icon.
Thank you very much.
