### ISSUE TITLE
How would you suggest installing it on Windows 11?

### ISSUE THREAD

**Issue by akarasulu** [ClementGre/ThreeFingersDragOnWindows#18]
Hi there! Thanks this is sooooo stress relieving. Was wondering how you recommend installing on Windows 11 to have your tray icon always available with 3-finger drags active?

Also a couple points that might help the Readme.md:

1. You have to disable the default 3-finger swipe functions via `Touchpad settings` for the drag to work (obvious but it does not occur to non-Windows users)
2. The exec command for DLL path was a little different for me:

```
dotnet exec .\bin\Debug\net6.0-windows\win-x64\ThreeFingersDragOnWindows.dll
```

Thanks again. Can't tell you how useful this little project is for people addicted to 3 finger drags.

**Comment by ClementGre** [comment]
Hi @akarasulu,

there is a .exe installer in the github release. If you want to make your own release, you can execute:
``dotnet publish --self-contained false``

Then, the app will be in ``.\bin\Debug\net6.0-windows\win-x64\publish\``

You have to keep together all of the files:
- ``ThreeFingersDragOnWindows.exe``
- ``ThreeFingersDragOnWindows.deps.json``
- ``ThreeFingersDragOnWindows.dll``
- ``ThreeFingersDragOnWindows.runtimeconfig.json``
- ``Resources\icon.ico``

You can copy these files in a directory into Program Files and create shortcuts to the executable in your application's shortcuts directory.

You can also make your own executable using Inno Setup and the [configuration file in the repo](https://github.com/ClementGre/ThreeFingersDragOnWindows/blob/main/inno_setup.iss).

I just updated the Readme so it is more clear now!
