### ISSUE TITLE
In some apps (uwp?) three fingers to drag doesn't work

### ISSUE THREAD

**Issue by k-kruglov** [ClementGre/ThreeFingersDragOnWindows#2]
I suppose it might be related to these apps being UWP, I've tried with Unigram (telegram client) and RSS tracker https://apps.microsoft.com/store/detail/rss-tracker/9N85PV1RJD6V?hl=en-us&gl=US or system settings app.

In all of them the standard text selection works (click + drag), when your app provided 3 fingers to drag doesn't.

Surface Book 1, windows 11.

p.s.

As also a mac user, I nearly started crying when I found out about your app on Reddit. I'm so used to this accessibility feature on macs, and switching to Windows was painful every time.

**Comment by ClementGre** [comment]
For moving and pressing the left click, I use the function ``mouse_event`` from ``user32.dll``, which effectively do not work in UWP applications.

I'll have to update the code a bit to make it work with UWP apps, using [input injection](https://docs.microsoft.com/en-us/windows/apps/design/input/input-injection).

Thanks for the report !

**Comment by k-kruglov** [comment]
Sounds that this is possible after all, which is great!

**Comment by lynnrinkui** [comment]
Can confirm that this does not work on multitasking view. I suppose it's because of the same reason?

**Comment by ClementGre** [comment]
I'm afraid I will not be able to update this app anymore.

I developed it in three days when I had a Windows laptop, but I don't have it anymore, and I figured out I had no wireless trackpad at home.

I hope someone will be able to fork this app to add the UWP support and fix some other bugs.
Thank you !

**Comment by MasaYan24** [comment]
FYI: Microsoft PowerPoint window is also not able to be dragged.

**Comment by gurinderhans** [comment]
Hi @k-kruglov, @MasaYan24, @lynnrinkui, I used this project as inspiration to write my own version, if you feel like, please try my version which I believe fixes all the issues you mention.
https://github.com/gurinderhans/threefingerdrag

@ClementGre, this is an amazing project, if you choose to, you can incorporate the fixes into your project :)

**Comment by ClementGre** [comment]
Hi, I just got a Windows laptop to work again on this project.

Thank you @gurinderhans, your app is amazing and fixes a lot of issues. I inspired myself of your code to fix issues in ThreeFingersDragOnWindows.
I do will not copy all of your code, but I'll try to fix these issues by looking at your code.

For this issue, I can't reproduce the bug on PowerPoint or in the system preferences, but I do can in the Win + Tab menu.

I was able to fix this issue by using input injection, from `user32.dll` (just like @gurinderhans did) :
> For moving and pressing the left click, I use the function `mouse_event` from `user32.dll`, which effectively do not work in UWP applications.
> 
> I'll have to update the code a bit to make it work with UWP apps, using [input injection](https://docs.microsoft.com/en-us/windows/apps/design/input/input-injection).

Then I guess this issue will not be present in the next release !

**Comment by michaelliunsky** [comment]
The program works fine on most UWP apps, such as

> Microsoft Store and
> Microsoft PowerPoint

But on Windows 11 22631.3672, I can't drag files in File Explorer
I hope someone will fix this problem.

**Comment by ClementGre** [comment]
Hi @michaelliunsky, can you reproduce the issue with TFDOW started with elevated privilege (as administrator)?

**Comment by michaelliunsky** [comment]
> Hi @michaelliunsky, can you reproduce the issue with TFDOW started with elevated privilege (as administrator)?

I solved the problem by accident by turning off my antivirus software. I think it may be the anti-virus software that blocks the normal operation of the program.

**Comment by wqtty** [comment]
> > > Hi [@michaelliunsky](https://github.com/michaelliunsky), can you reproduce the issue with TFDOW started with elevated privilege (as administrator)?
> > 
> > 
> > I solved the problem by accident by turning off my antivirus software. I think it may be the anti-virus software that blocks the normal operation of the program.
> 
> i've got the same issue and the same solution here, bro, r u using 360?

solved it,  in case someone came here after, here is the way

> turn on and off 360's “核晶防护”, if it's not working, try more times, i tried about 5 or 6 times, and leaved it off btw

https://blog.csdn.net/Frank_Yee/article/details/146240752

<img width="865" height="547" alt="Image" src="https://github.com/user-attachments/assets/58e6c8a4-907b-4ca0-be40-5913c0645c4f" />

**Comment by ClementGre** [comment]
That’s great, I should have thought about it!
