### ISSUE TITLE
Does not launch on Windows 10 x64 Pro - 10.0.19045 Build 19045 

### ISSUE THREAD

**Issue by m0rg5** [ClementGre/ThreeFingersDragOnWindows#23]
Does not open, nothing happens.

Net. 6 installed

**Comment by ClementGre** [comment]
ThreeFingersDragOnWindows v2.0 has just been released. In this version, the app is now bundled in a WinUI app that can be installed with a .Msix file, or from the Microsoft Store. You can try again as the app is now bundled in a brand new way.
[See release v2.0.1](https://github.com/ClementGre/ThreeFingersDragOnWindows/releases/tag/2.0.1)
Enjoy!
