### ISSUE TITLE
Make installer ask to add to windows startup

### ISSUE THREAD

**Issue by markhicken** [ClementGre/ThreeFingersDragOnWindows#24]
Nice work on this app! Works great on my Legion 5 pro with Windows 11!

What do you think about adding a step to the installer where it asks if you would like to autostart the app at windows login?

**Comment by ClementGre** [comment]
ThreeFingersDragOnWindows v2.0 just have been released. As the app is now a WinUI app that can be installed from the Microsoft Store or with a .Msix file, there is not really an "installer" anymore. However, this release now registers the app to run at system startup by default. This behavior can then be configured in the app Other Settings page.

[See release v2.0.1](https://github.com/ClementGre/ThreeFingersDragOnWindows/releases/tag/2.0.1)
Enjoy!
