### ISSUE TITLE
Automatically change windows settings

### ISSUE THREAD

**Issue by markhicken** [ClementGre/ThreeFingersDragOnWindows#25]
It would be nice if when the app starts, it would offer to automatically remove the 3-finger gesture settings.

**Comment by ClementGre** [comment]
ThreeFingersDragOnWindows v2.0 has just been released. This version addresses this issue by telling the user to disable the three-finger gestures in the settings, with a button that redirects to the Windows Touchpad Settings.
[See release v2.0.1](https://github.com/ClementGre/ThreeFingersDragOnWindows/releases/tag/2.0.1)
Enjoy!
