### ISSUE TITLE
Version number and auto-update?

### ISSUE THREAD

**Issue by markhicken** [ClementGre/ThreeFingersDragOnWindows#26]
What do you think about adding a version number to the UI along with an auto-update feature? At the very least it would be nice if it could check github to see if there is a newer release.

**Comment by ClementGre** [comment]
ThreeFingersDragOnWindows v2.0 has just been released. This new release is available on the Microsoft store, allowing for automatic updates. However, there is no update detection in the app itself.
[See release v2.0.1](https://github.com/ClementGre/ThreeFingersDragOnWindows/releases/tag/2.0.1)
Enjoy!
