### ISSUE TITLE
Enable UACskip when the program start with the system

### ISSUE THREAD

**Issue by sardanus** [ClementGre/ThreeFingersDragOnWindows#27]
I can't drag windows that belongs to admin apps. Instead I can drag everything if I start TFDOW as admin. The UAC prompt is annoying everytime I boot my pc, could you please add the skipUAC? This procedure already exists in many apps such as ccleaner

**Comment by ClementGre** [comment]
I guess this issue gives me the fix for #22.
Thank you @sardanus, I'll look into it while developing TFDOW v2.0!

**Comment by ClementGre** [comment]
ThreeFingersDragOnWindows v2.0 just have been released. This release addresses this issue, allowing the app to run as administrator, even at system startup, without any UAC prompt.
[See release v2.0.1](https://github.com/ClementGre/ThreeFingersDragOnWindows/releases/tag/2.0.1)
Enjoy!
