### ISSUE TITLE
Cannot Run : You must install .NET to run this application.

### ISSUE THREAD

**Issue by bietchetlien1995** [ClementGre/ThreeFingersDragOnWindows#3]
![image](https://user-images.githubusercontent.com/55707086/184079956-57f901e2-5555-4b55-aef2-73da5e4d4dde.png)
I tried to install from .NET 5, .NET6, .NET7, but it didnot workout

**Comment by Kibi1984** [comment]
Hello,
i have the same problem.
I installed .NET 5 and .NET 6 already.
But the alarm is still there.
Can you please check?

And thank you that you programm this.
I used a Macbook before and this is the only thing what i really miss on Windows. The Three finger drag. 

Best regards 

Kibi

**Comment by bietchetlien1995** [comment]
Yeah, hope someone knows a solution for this painful. Moved from macbook made me miss that function so much

**Comment by Kibi1984** [comment]
Hello bietchetlien1995,

i install the ASP.NET Core Runtime and Windows Desktop Runtime from this webside:
https://versionsof.net/core/6.0/6.0.0/
Now the alarm is gone.
But the Programm still dont open.
Maybe you can try.

Kibi

**Comment by bietchetlien1995** [comment]
@Kibi1984 I'm on Windows 11, how about you. I think I did install ytd but it didnot work

**Comment by Kibi1984** [comment]
Im also on Windows 11. 
Try to install the two things from this webside:
https://versionsof.net/core/6.0/6.0.0/
Then i dont get the alarm again.

But the Programm still dont open

**Comment by Kibi1984** [comment]
I hope this problem can fixed. Because i loved this function so much on my MacBook.

**Comment by ClementGre** [comment]
> Hello bietchetlien1995,
> 
> i install the ASP.NET Core Runtime and Windows Desktop Runtime from this webside:
> https://versionsof.net/core/6.0/6.0.0/
> Now the alarm is gone.
> But the Programm still dont open.
> Maybe you can try.
> 
> Kibi

Hi Kibi,

maybe the program had actually started but the configuration window hasn't been shown. Look at your taskbar right icons, maybe there is one for ThreeFingersDragOnWindows.

Otherwise, can you try to start the .exe file from a Terminal so we could eventually figure out what's the problem.

Thanks, Clément.

**Comment by Kibi1984** [comment]
I just look in the taskbar but there is nothing.
And when i start the programm in the terminal also nothing happen.
Do you have any other idea what i can test?
![Test](https://user-images.githubusercontent.com/111095361/184375440-4a0d5027-d656-4079-addf-ad85380ae346.png)

**Comment by Kibi1984** [comment]
But as soon as I start the program, windows problem reporting appears in the task manager

**Comment by Kibi1984** [comment]
I found something. Maybe this helps you.
![Uploading AlarmProtocoll.png…]()

**Comment by Kibi1984** [comment]
Name der fehlerhaften Anwendung: ThreeFingersDragOnWindows.exe, Version: 1.0.0.0, Zeitstempel: 0x62b2fac5
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.22000.832, Zeitstempel: 0x7efab3dc
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000004474c
ID des fehlerhaften Prozesses: 0x4448
Startzeit der fehlerhaften Anwendung: 0x01d8ae587a192653
Pfad der fehlerhaften Anwendung: C:\_EigeneProgramme\ThreeFingersDragOnWindows\ThreeFingersDragOnWindows.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: e948b963-ae0f-4676-9b9a-63632a88bb0e
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by Kibi1984** [comment]
Application: ThreeFingersDragOnWindows.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by Kibi1984** [comment]
Ok i found a solution.
First delete all ".Net X.X.X" Versions and components.
Second install this:
Windows Desktop Runtime (x64)
ASP.NET Core Runtime (x64)
from here:
https://versionsof.net/core/6.0/6.0.7/
After you did this the programm open without an alarm.
I think your Programm need .Net 6.0.7
Maybe you can check why is not working with higher Versions.

But thank you so much! For this function i was looking for very long time on Windows. ;)
You are great.

Best Regards

Kibi

**Comment by ClementGre** [comment]
I'm glad you found a solution, and I'm sorry for that, I'll try to figure out what is the problem when I'm back home.

Thank you, Clément.

**Comment by metal450** [comment]
I tried installing the runtime provided by the app's startup prompt (which was 6.0.11), & it didn't work (even after a reboot, just keeps showing the warning).  Likewise, I tried uninstalling it & manually installing 6.0.7, but no go unfortunately.

Is there any way to get this running, short of installing all of Visual Studio & the .net SDKs & building from scratch?

**Comment by metal450** [comment]
Nevermind, just got it.  Have to manually install both the runtime, and the Windows Desktop Runtime, per a comment above.  Thanks!

**Comment by jxwufan** [comment]
I got the same issue with .net runtime 5.0 and 1.2 installed, when i tried to run no error was shown, I have to uninstall all runtime and reinstall 6.0 to make it work

**Comment by metal450** [comment]
Hmm, I'm trying this out on a different laptop, somehow I can't get it running again. After the installer runs successfully, launching it yields this dialog:

![2024-08-10 21 39 49](https://github.com/user-attachments/assets/0eac02f8-6794-4caf-8690-ff6b837eb5b6)

I've installed both dotnet-runtime-6.0.7-win-x64 and windowsdesktop-runtime-6.0.7-win-x64 from https://versionsof.net/core/6.0/6.0.7/

**Comment by ClementGre** [comment]
I think this is not related to missing dependencies. You might file a new issue for that.

TFDOW does not interact much with the file system except for the configuration file then this error is a bit odd.
Do you have the same error if running TFDOW as Administrator?

**Comment by metal450** [comment]
Yup, same if running as administrator
