### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by kleuter** [ClementGre/ThreeFingersDragOnWindows#30]
Fresh Windows installation, fresh VS2022 Community installed.

```bash
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(447,5): error NETSDK1112: The runtime pack for Microsoft.Windows.SDK.NET.Ref was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'any'.
```

```bash
Restoring packages for C:\Users\me\Desktop\ThreeFingersDragOnWindows-main\ThreeFingersDragOnWindows\ThreeFingersDragOnWindows.csproj...
Restoring packages for C:\Users\me\Desktop\ThreeFingersDragOnWindows-main\ThreeFingersDragElevator\ThreeFingersDragElevator.csproj...
NU1213: The package Microsoft.Windows.SDK.NET.Ref 10.0.22621.31 has a package type DotnetPlatform that is incompatible with this project. 
NU1213: The package Microsoft.Windows.SDK.NET.Ref 10.0.22621.31 has a package type DotnetPlatform that is incompatible with this project. 
Package 'Microsoft.Windows.SDK.NET.Ref 10.0.22621.31' has a package type 'DotnetPlatform' that is not supported by project 'ThreeFingersDragElevator'.
Time Elapsed: 00:00:00.1049381
========== Finished ==========
```

**Comment by ClementGre** [comment]
Well, that is really strange as it woks well on my computer. Do you have all the libraries installed in the NuGet package manager?

You might check that you use the same versions as me:
![image](https://github.com/ClementGre/ThreeFingersDragOnWindows/assets/51322714/d6f863e0-730a-401d-a6df-b055adeaafc8)

You can also check that you have installed the UWP workload:
![](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/media/vs-2022/uwp-dev-workload.png?view=vs-2017&viewFallbackFrom=vs-2022)

You might be able to restore automatically the libraries used in this project with:
> dotnet restore

**Comment by kleuter** [comment]
![image](https://github.com/ClementGre/ThreeFingersDragOnWindows/assets/2600624/3babedfe-407c-4302-8df7-2cd458dc2284)

Again, it's Windows 10.

**Comment by ClementGre** [comment]
I am not able to reproduce your issue. However, I noticed a configuration issue (ThreeFingersDragElevator app decalared as Self-Contained as it should not). I corrected this, it might change the error you have. Normally, after opening the .sln in VS, the dependencies should be loaded automatically, and the project could be run. Also, make sure to build/run the app in Packaged mode.
