### ISSUE TITLE
Need more step-by-step explanation in "Build and Execute" section for light user

### ISSUE THREAD

**Issue by MasaYan24** [ClementGre/ThreeFingersDragOnWindows#31]
To encourage more users to use this wonderful tool, installation has to be explained in detail: step-by-step.

**Comment by ClementGre** [comment]
I guess users will just download the .Msix installer from GitHub or install from the Microsoft Store.
The Build and Execute section is addressed to developers who wan't to build the app from the source code. Then they should know how to run the project code in Visual Studio. The dependencies should be resolved automatically by the IDE, as long as the UWP toolkit is installed.
