### ISSUE TITLE
Auto Startup on system boot

### ISSUE THREAD

**Issue by linitfor** [ClementGre/ThreeFingersDragOnWindows#4]
Can the app add the option to auto startup on system boot ? This is an useful app. If it can combine into system auto boot, it will become more convenient.

**Comment by ClementGre** [comment]
The app does register itself in the system boot startup list. If it don't work for you, you can check in the Startup tab of the Task Manager (Ctrl + Shift + Esc).

**Comment by MasaYan24** [comment]
Just noting what I did. (and it starts automatically in my environment)
1. Create "bin" directory under my home directory.
2. Move whole directory of threeFingersDragOnWindows to "bin"
3. Create shortcut of executive under /path/to/ThreeFingersDragOnWindows/bin/Debug/net6.0-windows/ThreeFingersDragOnWindows.exe
4. Move shortcut to the directory where it is opend by Win+R -> shell:startup
