### ISSUE TITLE
Touchpad not detected, make sure to have a Windows Precision compatible touchpad

### ISSUE THREAD

**Issue by Phuclt20** [ClementGre/ThreeFingersDragOnWindows#40]
i use macbook pro 2015 a1502, install windows 10 and ThreeFingersDrag, It looks like the Touchpad Driver was installed on Bootcamp, not Windows, so ThreeFingersDrag couldn't detect the touchpad. 

Is there any solution for this?

**Comment by ClementGre** [comment]
ThreeFingersDragOnWindows can only work with Windows Precison Touchpad compatible devices.
A driver exists that allows Windows to recognize Apple touchpads as Precision touchapd, see #28.
Is it working with this driver?

**Comment by Phuclt20** [comment]
Just want to say thank you for your efforts guys, you're the man!
