### ISSUE TITLE
How to open the app configuration window?

### ISSUE THREAD

**Issue by MasaYan24** [ClementGre/ThreeFingersDragOnWindows#6]
I successfully build and run the program. It works well!
But I would like to change speed oof mouse cursor. It is so slow in my case.
Is there a way to change it after the 1st run since the configuration panel will not appear from the 2nd run of the executive file...

**Comment by ClementGre** [comment]
Yes, there is a way !
Just click the app icon on the right of the Windows task bar.

**Comment by MasaYan24** [comment]
Updated the README.md for this issue. #7
